Cbd.Fgw.Web/Areas/System/Controllers/DepartmentController.cs
using System.Linq;
using Abp.UI;
using System.Web.Mvc;
using Abp.Authorization;
using Cbd.Fgw.Application.System.Department;
using Cbd.Fgw.Application.System.Department.Dto;
using Cbd.Fgw.Web.Controllers;

namespace Cbd.Fgw.Web.Areas.System.Controllers {

    [AbpAuthorize("Administration")]
    public class DepartmentController : FgwControllerBase {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService) {
            _departmentService = departmentService;
        }

        [HttpGet]
        public ActionResult GetJsonByAsync(int? id) {
            var data = _departmentService.GetTreeAsync(id);
            return Json(data);
        }

        public ActionResult Index() {
            return View();
        }

        public ActionResult IndexList(DepartmentSearchInput input) {
            return Json(_departmentService.GetAll(input));
        }

        public ActionResult Details(int? id) {
            if (!id.HasValue) {
                throw new UserFriendlyException("未查询到部门");
            }

            return View(_departmentService.Get(id.Value));
        }

        public ActionResult Create() {
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll(), "Id", "DepartmentName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DepartmentCreateInput input) {
            if (ModelState.IsValid) {
                _departmentService.Create(input);
                ViewBag.Success = "success";
            }
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll().Where(d => d.Id != input.Id), "Id", "DepartmentName");

            return View();
        }

        [HttpGet]
        public ActionResult Edit(int? id) {
            if (!id.HasValue) {
                throw new UserFriendlyException($"未查询到部门");
            }
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll().Where(d => d.Id != id.Value), "Id", "DepartmentName");

            return View(_departmentService.Get(id.Value));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DepartmentCreateInput input) {
            if (ModelState.IsValid) {
                _departmentService.Edit(input);
                ViewBag.Success = "success";
            }
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll().Where(d => d.Id != input.Id), "Id", "DepartmentName");

            return View(_departmentService.Get(input.Id));
        }

        public ActionResult Delete(int? id) {
            if (!id.HasValue) {
                throw new UserFriendlyException("未查询到部门");
            }
            _departmentService.Delete(id.Value);

            return Json("success");
        }
    }
}

Cbd.Fgw.Web/Areas/System/Controllers/UserController.cs
using System;
using AutoMapper;
using System.Web.Mvc;
using Abp.AutoMapper;
using Cbd.Fgw.Core.System;
using Cbd.Fgw.Web.Controllers;
using System.Collections.Generic;
using Abp.Authorization;
using Cbd.Fgw.Application.System.Role;
using Cbd.Fgw.Application.System.User;
using Cbd.Fgw.Application.System.User.Dto;
using Cbd.Fgw.Application.System.Role.Dto;
using Cbd.Fgw.Application.System.Department;

namespace Cbd.Fgw.Web.Areas.System.Controllers {
    [AbpAuthorize("Administration")]
    public class UserController : FgwControllerBase {

        private readonly IUserService _userService;
        private readonly IRoleService _roleService;
        private readonly IDepartmentService _departmentService;

        public UserController(IUserService userService, IDepartmentService departmentService, IRoleService roleService) {
            _userService = userService;
            _departmentService = departmentService;
            _roleService = roleService;
        }

        public ActionResult Index() {
            return View();
        }

        [HttpGet]
        public ActionResult IndexList(UserSearchInput input) {
            return Json(_userService.GetUsers(input));
        }

        public ActionResult Details(int? id) {
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, "没有找到此用户");
            }
            var user = _userService.GetUser(id.Value);
            if (user == null) {
                return HttpNotFound();
            }

            return View(user);
        }

        public ActionResult Create() {
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll(), "Id", "DepartmentName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserCreateInput userCreateInput) {
            if (ModelState.IsValid) {
                _userService.CreateUser(userCreateInput);
                ViewBag.Success = string.Empty;
            }
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll(), "Id", "DepartmentName");

            return View();
        }

        public ActionResult Edit(int? id) {
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, "没有找到此用户");
            }
            var user = _userService.GetUser(id.Value);
            if (user == null) {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll(), "Id", "DepartmentName");
            Mapper.CreateMap<UserDto, UserCreateInput>();
            return View(user.MapTo<UserCreateInput>());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserUpdateInput userUpdateInput) {
            if (ModelState.IsValid) {
                _userService.UpdateUser(userUpdateInput);
                ViewBag.Success = string.Empty;
            }
            ViewBag.DepartmentId = new SelectList(_departmentService.GetAll(), "Id", "DepartmentName");

            return View();
        }

        [HttpPost]
        public ActionResult Delete(int? id) {
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, "没有找到此用户");
            }
            _userService.Delete(id.Value);

            return Json("success");
        }

        [HttpPost]
        public ActionResult ChangeActive(UserChangeActiveInput input) {
            if (ModelState.IsValid) {
                _userService.ChangeActive(input);
            }
            return Json("success");
        }

        public ActionResult Authorization(int? id) {
            if (!id.HasValue) {
                return new HttpStatusCodeResult(404, "没有找到此用户");
            }

            return View(_roleService.GetAll(new RoleDto()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Authorization(int id, string[] roles) {
            if (ModelState.IsValid) {
                var input = new UserAuthorizationInput {
                    Id = id,
                    Roles = new List<Role>()
                };
                foreach (var role in roles) {
                    input.Roles.Add(new Role { Id = Convert.ToInt32(role) });
                }
                _userService.SetAuthorization(input);
                ViewBag.Success = "success";
            }

            return View(_roleService.GetAll(new RoleDto()));
        }

    }
}

Cbd.Fgw.Web/Areas/System/Views/User/Authorization.cshtml
@model List<Cbd.Fgw.Application.System.Role.Dto.RoleDto>
@{
    ViewBag.Title = "用户授权";
}

@if (ViewBag.Success != null && ViewBag.Success == "success") {
    <script type="text/javascript">
        $.sys.alertClose("用户授权成功！", { icon: 1 });
    </script>
}

<div class="well">
    @using (Html.BeginForm("Authorization", "User", FormMethod.Post, new { @class = "form-horizontal" })) {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="checkbox">
                @foreach (var role in Model) {
                    <label>
                        <input type="checkbox" name="Roles" id="roles" value="@role.Id"> @role.RoleName
                    </label>
                }
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-raised">提交</button>
        </div>
    }
</div>

Cbd.Fgw.Web/Areas/System/Views/User/Create.cshtml
@model Cbd.Fgw.Application.System.User.Dto.UserCreateInput
@{
    ViewBag.Title = "创建用户";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles{
    <link href="~/Content/plugs/Ztree/metroStyle.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/plugs/Ztree/jquery.ztree.all.min.js"></script>

    @if (!ViewData.ModelState.IsValid) {
        <script>
            var error = adderror('@Html.ValidationMessageFor(u => u.UserName, "", new {@class = "text-danger"})') +
                adderror('@Html.ValidationMessageFor(u => u.RealName, "", new {@class = "text-danger"})') +
                adderror('@Html.ValidationMessageFor(u => u.Pwd, "", new {@class = "text-danger"})') +
                adderror('@Html.ValidationMessageFor(u => u.PwdAgain, "", new {@class = "text-danger"})');
            $.sys.showError(error);

        </script>
    }
    else {
        if (ViewBag.Success != null) {
            <script>
                $(function() {
                    $.sys.alertClose("用户创建成功！", { icon: 2 });
                });
            </script>
        }
    }

    <script type="text/javascript">
        var setting = {
            view: {
                selectedMulti: false
            },
            async: {
                enable: true,
                type: "get",
                url: '@Url.Action("GetJsonByAsync", "Department")',
                autoParam: ["id"],
                dataFilter: filter
            },
            callback: {
                beforeClick: BeforeCheck
            }
        };

        function filter(treeId, parentNode, childNodes) {
            if (!childNodes) return null;
            for (var i = 0, l = childNodes.length; i < l; i++) {
                childNodes[i].name = childNodes[i].name.replace(/\.n/g, '.');
            }
            return childNodes;
        }


        function BeforeCheck(treeId, treeNode) {
            parent.layer.msg("选中了：" + treeNode.name, { icon: 0 });
            $('#DepartmentId').val(treeNode.id);
        }

        $(document).ready(function() {
            $.fn.zTree.init($("#departmentTree"), setting);
        });

    </script>
}

<div class="well bs-component">
    @using (Html.BeginForm("CreateUser", "User", FormMethod.Post, new { @class = "form-horizontal" })) {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(u => u.UserName, new { @class = "col-xs-3 control-label", @for = "UserName" })
            <div class="col-xs-8">
                @Html.EditorFor(u => u.UserName, new { htmlAttributes = new { @class = "form-control", @id = "UserName" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.RealName, new { @class = "col-xs-3 control-label", @for = "RealName" })
            <div class="col-xs-8">
                @Html.EditorFor(u => u.RealName, new { htmlAttributes = new { @class = "form-control", @id = "RealName" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.Pwd, new { @class = "col-xs-3 control-label", @for = "Pwd" })
            <div class="col-xs-8">
                @Html.EditorFor(model => model.Pwd, new { htmlAttributes = new { @class = "form-control", @id = "Pwd" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.PwdAgain, new { @class = "col-xs-3 control-label", @for = "PwdAgain" })
            <div class="col-xs-8">
                @Html.EditorFor(u => u.PwdAgain, new { htmlAttributes = new { @class = "form-control", @id = "PwdAgain" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.DepartmentId, new { @class = "col-xs-3 control-label", @for = "PwdAgain" })
            <div class="col-xs-8">
                @Html.HiddenFor(u => u.DepartmentId)
                <ul id="departmentTree" class="ztree"></ul>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.IsActive, new { @class = "col-xs-3 control-label", @for = "IsActive" })
            <div class="col-xs-8">
                <div class="checkbox">
                    <label>
                        @Html.EditorFor(u => u.IsActive, new { htmlAttributes = new { @id = "IsActive" } })
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-3 col-xs-8">
                <button type="submit" class="btn btn-raised">提交</button>
            </div>
        </div>
    }
</div>

Cbd.Fgw.Web/Areas/System/Views/User/Details.cshtml
@using Cbd.Common.HtmlHelper
@model Cbd.Fgw.Application.System.User.Dto.UserDto
@{
    ViewBag.Title = "用户详情";
}

<div class="well bs-component">
    @using (Html.BeginForm("CreateUser", "User", FormMethod.Post, new { @class = "form-horizontal" })) {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(u => u.UserName, new { @class = "col-xs-3 control-label", @for = "UserName" })
            <div class="col-xs-8 div-details-info">
                @Html.DisplayFor(u => u.UserName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.RealName, new { @class = "col-xs-3 control-label", @for = "RealName" })
            <div class="col-xs-8 div-details-info">
                @Html.DisplayFor(u => u.RealName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.DepartmentId, new { @class = "col-xs-3 control-label", @for = "DepartmentId" })
            <div class="col-xs-8 div-details-info">
                @Html.DisplayFor(u => u.Department.DepartmentName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.Roles, new { @class = "col-xs-3 control-label", @for = "DepartmentId" })
            <div class="col-xs-8 div-details-info">
                @foreach (var role in Model.Roles) {
                    @role.RoleName
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.IsActive, new { @class = "col-xs-3 control-label", @for = "IsActive" })
            <div class="col-xs-8 div-details-info">
                @Html.Iischeck(Model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.IsSystem, new { @class = "col-xs-3 control-label", @for = "IsActive" })
            <div class="col-xs-8 div-details-info">
                @Html.Iischeck(Model.IsSystem)
            </div>
        </div>
    }
</div>

Cbd.Fgw.Web/Areas/System/Views/User/Edit.cshtml
@model Cbd.Fgw.Application.System.User.Dto.UserCreateInput
@{
    ViewBag.Title = "更新用户";
}

@section scripts{
    @if (!ViewData.ModelState.IsValid) {
        <script>
            var error = adderror('@Html.ValidationMessageFor(u => u.UserName, "", new {@class = "text-danger"})') +
                adderror('@Html.ValidationMessageFor(u => u.RealName, "", new {@class = "text-danger"})') +
                adderror('@Html.ValidationMessageFor(u => u.Pwd, "", new {@class = "text-danger"})') +
                adderror('@Html.ValidationMessageFor(u => u.PwdAgain, "", new {@class = "text-danger"})');
            $.sys.showError(error);
        </script>
    }
    else {
        if (ViewBag.Success != null) {
            <script>
                $(function () {
                    $.sys.alertClose("用户修改成功！", { icon: 2 });
                });
            </script>
        }
    }
}

<div class="well bs-component">
    @using (Html.BeginForm("Edit", "User", FormMethod.Post, new { @class = "form-horizontal" })) {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(u => u.UserName, new { @class = "col-xs-3 control-label", @for = "UserName" })
            <div class="col-xs-8">
                @Html.EditorFor(u => u.UserName, new { htmlAttributes = new { @class = "form-control", @id = "UserName" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.RealName, new { @class = "col-xs-3 control-label", @for = "RealName" })
            <div class="col-xs-8">
                @Html.EditorFor(u => u.RealName, new { htmlAttributes = new { @class = "form-control", @id = "RealName" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.Pwd, new { @class = "col-xs-3 control-label", @for = "Pwd" })
            <div class="col-xs-8">
                @Html.EditorFor(model => model.Pwd, new { htmlAttributes = new { @class = "form-control", @id = "Pwd" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.PwdAgain, new { @class = "col-xs-3 control-label", @for = "PwdAgain" })
            <div class="col-xs-8">
                @Html.EditorFor(u => u.PwdAgain, new { htmlAttributes = new { @class = "form-control", @id = "PwdAgain" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.IsActive, new { @class = "col-xs-3 control-label", @for = "IsActive" })
            <div class="col-xs-8">
                <div class="checkbox">
                    <label>
                        @Html.EditorFor(u => u.IsActive, new { htmlAttributes = new { @id = "IsActive" } })
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-3 col-xs-8">
                <button type="submit" class="btn btn-raised">提交</button>
            </div>
        </div>
    }
</div>

Cbd.Fgw.Web/Areas/System/Views/User/Index.cshtml
@{
    ViewBag.Title = "用户列表";
}

<div class="well">
    <form role="form">
        <div id="toolbar">
            <div class="form-group label-floating pull-left">
                <label for="i5p" class="control-label"><i class="fa fa-search"></i> 输入用户名，按回车键搜索</label>
                <input type="text" class="form-control" id="i5p" style="width: 400px;">
            </div>

            <div class="btn-group form-group pull-right">
                <a href="javascript:craete()" class="btn btn-primary btn-raised">创建新用户</a>
                <div class="btn-group">
                    <a href="javascript:void(0)" data-target="#" class="btn btn-raised btn-primary dropdown-toggle" data-toggle="dropdown">
                        更多操作
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="javascript:void(0)">删除用户</a></li>
                        <li class="divider"></li>
                        <li><a href="javascript:void(0)">禁用</a></li>
                        <li><a href="javascript:void(0)">启用</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </form>

    <table class="table table-striped" id="table"></table>

</div>

@section scripts
{
    <script type="text/javascript">
        $table = $('#table');

        function craete() {
            $.sys.create({
                content: '@Url.Action("Create")',
                end: function () {
                    $table.bootstrapTable('refresh');
                }
            });
        }

        function details(id) {
            $.sys.detail({
                content: '@Url.Action("Details")\\' + id
            });
        }

        function edit(id) {
            $.sys.edit({
                content: '@Url.Action("Edit")\\' + id,
                end: function () {
                    $table.bootstrapTable('refresh');
                }
            });
        }

        function del(name, id) {
            $.sys.del("是否删除用户【" + name + "】？", function () {
                $.post('@Url.Action("Delete")', { id: id }, function (obj) {
                    $table.bootstrapTable('refresh');
                    if (obj === 'success') {
                        toastr.warning('用户【' + name + '】，删除成功！', '系统消息');
                    }
                });
            });
        }

        function Authorization(id) {
            $.sys.otherWindow({
                title: "分配角色",
                area: ['900px', "600px"],
                content: '@Url.Action("Authorization")\\' + id,
                end: function () {
                    $table.bootstrapTable('refresh');
                }
            });
        }

        var changeActive = function (id,obj) {
            var state = $(obj).prop("checked");
            $.post("@Url.Action("ChangeActive")", {
                id: id,
                isActive: state
            }, function(obj) {
                if (obj === 'success') {
                    if (!state) {
                        toastr.warning('用户禁用成功', '系统消息');
                    } else {
                        toastr.success('用户激活成功', '系统消息');
                    }
                }
            });
        }

        $(function() {
            $table.bTable({
                url: '@Url.Action("IndexList")'
            },
            [
                {
                    field: 'id',
                    title: '编号'
                },
                {
                    field: 'userName',
                    title: '用户名'
                },
                {
                    field: 'realName',
                    title: '真实姓名'
                },
                {
                    field: 'roles',
                    title: '角色',
                    align: 'left',
                    formatter: function(value, row, index) {
                        var returns = "";
                        for (var i = 0; i < value.length; i++) {
                            if (value[i].isSystem) {
                                returns += '<i class="fa fa-lock"></i> ';
                            }
                            returns += value[i].roleName + "、";
                        }
                        return returns.substring(0, returns.length - 1);
                    }
                },
                {
                    field: 'department.departmentName',
                    title: '部门名称'
                },
                {
                    field: 'isActive',
                    title: '用户状态',
                    formatter: function(value, row, index) {
                        var isActive = value ? "checked" : "";
                        var isSystem = row.isSystem ? "disabled" : "";
                        return [
                            '<div class="togglebutton btn-noline">' +
                            '<label>' +
                            '<input onclick="changeActive(' + row.id + ',this)" type="checkbox" ' + isActive + ' ' + isSystem + '>' +
                            '</label>' +
                            '</div>'
                        ].join('');
                    }
                },
                {
                    field: 'tool',
                    title: '操作',
                    formatter: function(value, row, index) {
                        var isSystem = row.isSystem ? "disabled" : "";
                        return [
                            '<button type="button" class="btn btn-noline btn-xs btn-raised btn-primary" onclick="details(' + row.id + ')">详情</button>' +
                            '<button ' + isSystem + ' type="button" class="btn btn-noline btn-xs btn-raised btn-warning" onclick="Authorization(' + row.id + ')">角色</button>' +
                            '<button ' + isSystem + ' type="button" class="btn btn-noline btn-xs btn-raised btn-warning" onclick="edit(' + row.id + ')">修改</button>' +
                            '<button ' + isSystem + ' type="button" class="btn btn-noline btn-xs btn-raised btn-danger" onclick="del(\'' + row.userName + '\',' + row.id + ')">删除</button>'
                        ].join('');
                    }
                }
            ]);
        });
    </script>
}